### ISSUE TITLE
CLEAR without OK due to disconnect

### ISSUE THREAD

**Issue by threez** [pace/openfsc-spec#2]
### Problem

The server sends a `CLEAR` to the client the client acks the `CLEAR` with `OK` but the server doesn't see the `OK` because of a connection drop. In case the transaction is not reported again, the server doesn't know if it was because the transaction was paid in the store or because it was already cleared with the first call.

### Solution

Explicitly describe the race and how it is remediated.

**Comment by pnull** [comment]
Proposal PR has been merged: #3
